import { securityAnalysis } from "../analysis/securityRisk";
import { dependencyGraphAnalysis } from "../analysis/dependencyGraph";
import { DependencySummaryCards } from "./DependencySummaryCards";
import { severityClass } from "./severity";

type SecurityLensProps = {
  summaryCopy: string;
  summaryTitle: string;
};

export function SecurityLens({ summaryCopy, summaryTitle }: SecurityLensProps) {
  const highSignalFindings = securityAnalysis.findings.slice(0, 6);

  return (
    <section className="pane graph-map security-lens" aria-labelledby="graph-map-title">
      <div className="pane-heading">
        <p className="eyebrow" id="active-lens-label">
          Security lens
        </p>
        <h2 id="graph-map-title">Danger Path Map</h2>
      </div>

      <DependencySummaryCards
        ariaLabel="Security danger path summary"
        metrics={[
          { label: "Danger paths", value: securityAnalysis.summary.dangerPathCount },
          { label: "Trust crossings", value: securityAnalysis.summary.trustBoundaryCrossingCount },
          { label: "External transfers", value: securityAnalysis.summary.externalTransferCount },
          { label: "Secret access", value: securityAnalysis.summary.secretAccessCount }
        ]}
      />

      <div className="security-danger-map" aria-label="Security danger path map">
        <div className="danger-path-list">
          <h3>New danger paths</h3>
          {securityAnalysis.dataFlows
            .filter((flow) => flow.introducedByChange)
            .map((flow) => {
              const from = dependencyGraphAnalysis.nodes.find((node) => node.id === flow.fromNodeId);
              const to = dependencyGraphAnalysis.nodes.find((node) => node.id === flow.toNodeId);

              return (
                <article className="danger-path" key={flow.id}>
                  <span>{flow.classification}</span>
                  <strong>
                    {from?.label ?? flow.fromNodeId} {"->"} {to?.label ?? flow.toNodeId}
                  </strong>
                  <p>{flow.evidence}</p>
                </article>
              );
            })}
        </div>

        <div className="security-finding-stack">
          <h3>Security findings</h3>
          {highSignalFindings.map((finding) => (
            <article className="security-finding" key={finding.id}>
              <span className={`severity ${severityClass(finding.severity)}`}>
                {finding.severity}
              </span>
              <div>
                <strong>{finding.title}</strong>
                <p>{finding.evidence}</p>
              </div>
            </article>
          ))}
        </div>
      </div>

      <div className="dependency-findings security-summary">
        <h3>{summaryTitle}</h3>
        <p>{summaryCopy}</p>
        <p>
          Security Lens answers: What new danger paths did this change introduce? It uses data
          classification, dependency edges, and AI-generated bypass signals.
        </p>
      </div>
    </section>
  );
}

export const securityFindings = securityAnalysis.findings;
